BACKBLAZE_KEY_ID="BACKBLAZE_KEY_ID" \
BACKBLAZE_APPLICATION_KEY="BACKBLAZE_APPLICATION_KEY/vqI" \
BACKBLAZE_BUCKET_REGION="BACKBLAZE_BUCKET_REGION" \
BACKBLAZE_BUCKET_NAME="BACKBLAZE_BUCKET_NAME" \
GPG_RECIPIENT="GPG_RECIPIENT" \
cargo run 