# NTFY_CA_FILE_PATH="" \

BACKBLAZE_KEY_ID="BACKBLAZE_KEY_ID" \
BACKBLAZE_APPLICATION_KEY="BACKBLAZE_APPLICATION_KEY/vqI" \
BACKBLAZE_BUCKET_REGION="BACKBLAZE_BUCKET_REGION" \
BACKBLAZE_BUCKET_NAME="BACKBLAZE_BUCKET_NAME" \
GPG_RECIPIENT="GPG_RECIPIENT" \
DO_NOT_CLEANUP="true" \
NTFY_URL="https://ntfy.sh/example" \
cargo run
